name = "click_laser"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
binding = "sale"
bucket_name = "seu-bucket-de-vendas"

[[r2_buckets]]
binding = "creator"
bucket_name = "seu-bucket-de-criadores"
