name = "click_laser"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
binding = "sale"
bucket_name = "click-laser-products-sale"

[[r2_buckets]]
binding = "creator"
bucket_name = "click-laser-products-creator"
